---

users:
  - username: foo
    name: Foo Barrington
    groups: []
    uid: 1003
    ssh_keys:
      - ssh_pub_keys/centos.pub
# users_deleted:
#   - username: foo
#     uid: 1003

manage_ssh_keys:
  - remote_user: foo #define username on remote system to add defined keys to
    present: true  #defines if ssh key should be added or removed
    ssh_keys:  #define key(s) to add to remote username
      - ssh_pub_keys/ubuntu.pub
      - ssh_pub_keys/centos.pub
  # - remote_user: foo
  #   present: false
  #   ssh_keys:
  #     - ssh_pub_keys/centos.pub
