language: python
python:
  - "2.7"
# command to install dependencies
install:
  - sudo pip install -r requirements.txt
# command to run tests
script:
  - echo "Hello World"
  - echo ${TEST}
after_success:
   if ([[ "${TRAVIS_BRANCH}" == "master" ]] || [[ ! -z "${TRAVIS_TAG}" ]]) && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
     echo "This will deploy!"
     echo ${TRAVIS_TAG}
   else
     echo "This will not deploy!"
   fi
